import json
import re
import asyncio
import subprocess
import shutil
import requests
import time
import replicate
import os
import io
from pathlib import Path
from io import BytesIO
from PIL import Image
from groq import Groq
from pydub import AudioSegment
from elevenlabs.client import ElevenLabs
from elevenlabs import save
from .state import VideoState, SceneData
from dotenv import load_dotenv
from stability_sdk import client
import stability_sdk.interfaces.gooseai.generation.generation_pb2 as generation

load_dotenv()

groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
elevenlabs_client = ElevenLabs(api_key=os.getenv("ELEVENLABS_API_KEY"))
replicate_client = replicate.Client(api_token=os.getenv("REPLICATE_API_KEY"))
stability_api = client.StabilityInference(key=os.getenv("STABILITY_API_KEY"))


# helper function to extract JSON from text (handles code blocks and partial JSON)
def extract_json(text: str):
    try:
        return json.loads(text)
    except:
        # Find first valid JSON object
        stack = []
        start = None
        
        for i, char in enumerate(text):
            if char == "{":
                if start is None:
                    start = i
                stack.append(char)
            elif char == "}":
                stack.pop()
                if not stack and start is not None:
                    try:
                        return json.loads(text[start:i+1])
                    except:
                        continue
        
        raise ValueError("No valid JSON found")


async def research_topic(state: VideoState) -> VideoState:
    topic = state["topic"]
    
    base_dir = Path(f"../output/{topic}")
    base_dir.mkdir(parents=True, exist_ok=True)

    script_path = base_dir / "script" / f"{topic}.json"
    script_path.parent.mkdir(parents=True, exist_ok=True)

    # SKIP if already exists
    if script_path.exists():
        print("⏭️ Using cached script...")
        
        with open(script_path, "r", encoding="utf-8") as f:
            data = json.load(f)

    else:
        prompt = f"""Create an engaging educational script about: {topic}

For each scene, provide:
- text: Natural narration (2-4 sentences, conversational)
- visual_type: Always use "diagram" for slide generation
- visual_data:
- heading: Ultra-concise title (2-4 words max)
- points: 2-3 key takeaways (5-8 words each)
- description: Visual style hint (e.g., "neural network architecture", "data flow diagram")

Example:
    {{
    "title": "Video title",
    "description": "Short YouTube description",
    "tags": ["tag1", "tag2"],
    "scenes": [
        {{
        "text": "2-4 sentence narration",
        "visual_type": "diagram",
        "visual_data": {{
            "description": "visual hint"
        }}
        }}
    ]
    }}

Create 10-12 scenes. Keep headings SHORT."""

        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=4000
        )
        
        content = response.choices[0].message.content.strip()

        if content.startswith("```"):
            content = re.sub(r'^```(?:json)?\s*', '', content)
            content = re.sub(r'\s*```\s*$', '', content)
        
        print(f"\n{'='*60}")
        print("✅ Script generated by Groq")
        print(f"{'='*60}\n")

        data = extract_json(content)

        # 💾 SAVE
        with open(script_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)

    # ✅ rest stays same
    state["script"] = [SceneData(
        timestamp=0,
        duration=0,
        text=scene["text"],
        visual_type=scene["visual_type"],
        visual_data=scene.get("visual_data")
    ) for scene in data["scenes"]]

    state["metadata"] = {
        "title": data["title"],
        "description": data["description"],
        "tags": data["tags"]
    }

    return state

async def generate_visuals(state: VideoState) -> VideoState:
    """Generate beautiful educational slide images using Replicate SDXL"""
    
    print(f"🎨 Generating visuals with Replicate SDXL...")
    
    visuals_dir = Path(f"../video-renderer/public/visuals")
    visuals_dir.mkdir(parents=True, exist_ok=True)
    
    loop = asyncio.get_event_loop()
    
    for i, scene in enumerate(state["script"]):
        # Generate images for all scenes (not just diagram/image)
        image_path = visuals_dir / f"scene_{i:02d}.png"
        
        # Skip if already exists
        if image_path.exists():
            print(f"   ⏭️  Scene {i+1}: already exists, skipping...")
            if not scene.visual_data:
                scene.visual_data = {}
            scene.visual_data['image_path'] = f"/visuals/{image_path.name}"
            continue
        
        print(scene.visual_data)
        print(scene.text)

        # Extract key info from scene
        description = scene.visual_data.get('description', '') if scene.visual_data else ''

        # Build prompt for beautiful educational slide
        prompt = f"""Professional educational slide design for tech presentation.

Title: {description}
Content: {scene.text}

Style: Modern minimal design, dark navy/purple gradient background, clean typography, small amount of text, geometric abstract shapes, tech-themed icons, professional color scheme with purple/blue accents, high contrast, cinematic lighting, premium quality.

Layout: Title at top, 3-4 bullet points maximum, relevant tech visualization or diagram in background, plenty of negative space, elegant and uncluttered.

NO photographs, NO realistic images, ONLY relevant geometric design with minimal text overlay."""

        print(f"   Generating slide for scene {i+1}: {description}")
        
        def generate_image_sd35(prompt_text, output_path, retries=2):
            url = "https://api.stability.ai/v2beta/stable-image/generate/core"
            
            headers = {
                "Authorization": f"Bearer {os.getenv('STABILITY_API_KEY')}",
                "Accept": "image/*"
            }

            for attempt in range(retries):
                try:
                    files = {
                        "prompt": (None, prompt_text),
                        "model": (None, "sd3.5-flash"),  # 🔥 your model
                        "aspect_ratio": (None, "16:9"),
                        "output_format": (None, "png"),
                        "cfg_scale": (None, "5"),
                        "negative_prompt": (None, "photo, realistic, people, faces, text, watermark, blurry")
                    }

                    response = requests.post(url, headers=headers, files=files, timeout=60)

                    if response.status_code == 200:
                        with open(output_path, "wb") as f:
                            f.write(response.content)
                        return True
                    else:
                        print(f"   ⚠️ API Error: {response.status_code} - {response.text}")

                except Exception as e:
                    print(f"   ⚠️ Attempt {attempt+1} failed: {str(e)}")
                    if attempt < retries - 1:
                        time.sleep(3)

            return False
        
        success = await loop.run_in_executor(
            None,
            generate_image_sd35,
            prompt,
            str(image_path)
        )
        
        if success:
            if not scene.visual_data:
                scene.visual_data = {}
            scene.visual_data['image_path'] = f"/visuals/{image_path.name}"
            print(f"   ✅ Generated: {image_path.name}")
        else:
            print(f"   ⚠️  Skipping scene {i+1} (generation failed)")
    
    return state

async def generate_audio(state: VideoState) -> VideoState:
    """Generate TTS audio per scene and measure actual durations"""
    
    print(f"🎤 Generating audio with ElevenLabs...")
    
    script = state["script"]
    topic = state["topic"]

    base_dir = Path(f"../output/{topic}")

    audio_path = base_dir / "audio" / f"{topic}_scenes"
    audio_path.mkdir(parents=True, exist_ok=True)
    
    audio_segments = []
    cumulative_time = 0
    
    loop = asyncio.get_event_loop()
    
    for i, scene in enumerate(script):
        scene_audio_path = audio_path / f"scene_{i:02d}.mp3"
        
        # 🔥 SKIP if already exists
        if scene_audio_path.exists():
            print(f"   ⏭️ Scene {i+1}: already exists, skipping...")
        else:
            def generate_scene_audio(text, path):
                audio = elevenlabs_client.text_to_speech.convert(
                    text=text,
                    voice_id="oYYSkpzqAvGfHhMWLizs",
                    model_id="eleven_turbo_v2_5"
                )
                save(audio, str(path))
            
            await loop.run_in_executor(
                None,
                generate_scene_audio,
                scene.text,
                scene_audio_path
            )
        
        # ✅ Always load (either existing or newly created)
        audio = AudioSegment.from_mp3(str(scene_audio_path))
        duration_seconds = len(audio) / 1000.0

        scene.timestamp = cumulative_time
        scene.duration = duration_seconds

        print(f"   Scene {i+1}: {duration_seconds:.1f}s")

        audio_segments.append(audio)
        cumulative_time += duration_seconds
    
    # Concatenate
    final_audio = sum(audio_segments)
    final_path = audio_path.parent / f"{topic}_full_audio.mp3"
    final_audio.export(str(final_path), format="mp3")
    
    print(f"\n✅ Audio generated: {final_path}")
    print(f"📊 Total duration: {cumulative_time:.1f}s")
    
    state["audio_path"] = str(final_path)
    state["metadata"]["total_duration"] = cumulative_time
    
    return state

def render_video(state: VideoState) -> VideoState:
    """Call Remotion to render video"""

    base_dir = Path(f"../output/{state['topic']}")

    # Copy audio to video-renderer public folder
    filename = f"{state['topic'].replace(' ', '_')}.mp3"
    public_audio_path = Path(f"../video-renderer/public/{filename}").resolve()
    shutil.copy(state["audio_path"], public_audio_path)
    
    # Save script for Remotion
    script_data = {
        "scenes": [scene.dict() for scene in state["script"]],
        "audio_path": f"/{filename}",
        "metadata": state["metadata"]
    }
    
    # Debug: Print timing info
    print(f"\n📊 Scene Timing Breakdown:")
    for i, scene in enumerate(state["script"]):
        print(f"   Scene {i+1}: {scene.timestamp:.1f}s → {scene.timestamp + scene.duration:.1f}s ({scene.duration:.1f}s)")
    
    # Render with Remotion
    video_path = base_dir/"videos"/f"{state['topic']}.mp4"
    video_path.parent.mkdir(parents=True, exist_ok=True)
    
    print(f"\n🎬 Rendering video with Remotion...")
    
    # Save props for Remotion
    props_path = "props.json"
    props_full_path = Path("../video-renderer/props.json").resolve()

    with open(props_full_path, "w") as f:
        json.dump({"scriptData": script_data}, f, indent=2)

    cmd = [
        "npx", "remotion", "render",
        "src/index.ts", "AIVideo",
        str(video_path),
        f"--props={props_path}"
    ]

    process = subprocess.Popen(
    " ".join(cmd),
    cwd="../video-renderer",
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True,
    shell=True,
    encoding="utf-8",
    errors="ignore",
    bufsize=1
    )

    print(f"🎬 Rendering in progress...\n")

    # Stream output in real-time
    for line in process.stdout:
        line = line.strip()
        if line:
            # Show progress lines
            if "%" in line or "Rendering" in line or "Frame" in line:
                print(f"   {line}")
            elif "Encoded" in line or "Done" in line:
                print(f"   ✅ {line}")

    process.wait()
    result_code = process.returncode

    if result_code != 0:
        state["error"] = f"Remotion failed with code {result_code}"
        print(f"❌ Remotion error")
        return state

def human_review(state: VideoState) -> VideoState:
    """Wait for human approval"""
    print(f"\n{'='*60}")
    print(f"VIDEO READY FOR REVIEW")
    print(f"{'='*60}")
    print(f"Topic: {state['topic']}")
    print(f"Video: {state.get('video_path', 'N/A')}")
    print(f"Title: {state['metadata']['title']}")
    print(f"\nReview the video and approve/reject")
    print(f"{'='*60}\n")
    
    response = input("Approve for upload? (yes/no): ").lower()
    state["approved"] = response == "yes"
    
    return state

def upload_youtube(state: VideoState) -> VideoState:
    """Upload video to YouTube"""
    if not state["approved"]:
        print("❌ Upload cancelled by user")
        return state
    
    print(f"✅ Video would be uploaded: {state['metadata']['title']}")
    print(f"   (YouTube upload not implemented yet)")
    return state